<a href="https://colab.research.google.com/github/PrivateerDev/BanquitoBD/blob/main/cuadernillo_bases_de_datos_desde_cero_colab_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introducción a Bases de Datos desde cero

---

En este material trabajaremos:

- qué es una base de datos,
- por qué se usa en sistemas reales,
- qué son tablas, registros y campos,
- cómo se hacen operaciones de **altas, bajas, cambios y búsquedas**,
- cómo se diseña una base de datos sencilla,
- y cómo conectar estas ideas con un **sistema web**.

La intención es que no solo memorices comandos, sino que entiendas **para qué sirven** y **cómo se aplican** en un proyecto real.

---

## Proyecto Ejemplo

A lo largo del cuadernillo tomaremos como ejemplo un sistema web que permite:

- registrar información,
- editar información,
- eliminar información,
- buscar información.

Es decir, un sistema de **altas, bajas, cambios y búsquedas**.

En bases de datos, eso se traduce principalmente en las operaciones:

- **INSERT** → alta  
- **DELETE** → baja  
- **UPDATE** → cambio  
- **SELECT** → búsqueda  

Sí: CRUD con traje formal.

# 1. ¿Qué es una base de datos?

Una **base de datos** es un conjunto de datos organizados de forma que puedan almacenarse, consultarse y modificarse fácilmente.

Piensa en una libreta donde guardas nombres, correos y teléfonos.  
Eso ya es una forma sencilla de almacenar datos.  
La diferencia es que una base de datos permite hacerlo de manera mucho más ordenada, rápida y segura.

## Ejemplo cotidiano

Imagina un sistema escolar.  
Se necesita guardar:

- alumnos,
- profesores,
- materias,
- calificaciones,
- horarios.

Si todo eso se escribiera en archivos sueltos o en hojas dispersas, sería un caos.  
La base de datos ayuda a que toda esa información quede organizada y relacionada.

## ¿Por qué son importantes?

Porque permiten:

- almacenar grandes cantidades de información,
- evitar duplicidad innecesaria,
- buscar datos rápidamente,
- actualizar información sin rehacer todo,
- compartir información entre usuarios y sistemas.

# 2. Conceptos básicos

## Tabla
Una **tabla** almacena datos de un mismo tipo.

Ejemplo: una tabla llamada `usuarios`.

## Campo o columna
Es cada atributo que se guarda.

Ejemplo en `usuarios`:

- id
- nombre
- correo
- edad

## Registro o fila
Es cada elemento almacenado dentro de la tabla.

Ejemplo:

| id | nombre | correo | edad |
|---|---|---|---|
| 1 | Ana | ana@gmail.com | 22 |

## Clave primaria
Es un campo que identifica de manera única a cada registro.

Por ejemplo: `id`.

No debería repetirse ni quedar vacío.

## Relación
Es la conexión entre tablas.

Ejemplo:
- una tabla `clientes`
- una tabla `pedidos`

Cada pedido pertenece a un cliente.  
Ahí ya existe una relación.

---

## Ejemplo visual rápido

**Tabla usuarios**
| id | nombre | correo |
|---|---|---|
| 1 | Luis | luis@gmail.com |
| 2 | María | maria@gmail.com |

Aquí:
- `id`, `nombre`, `correo` son columnas
- cada renglón es un registro
- `id` puede funcionar como clave primaria

# 3. ¿Qué es SQL?

**SQL** significa **Structured Query Language**.  
Es el lenguaje que se usa para trabajar con bases de datos relacionales.

Con SQL podemos:

- crear tablas,
- insertar datos,
- consultar información,
- actualizar registros,
- eliminar registros.

En pocas palabras: es el idioma oficial del mundo relacional.

En este cuadernillo usaremos **SQLite**, porque funciona muy bien en Colab y no requiere instalación compleja.

# 4. Preparación del entorno en Google Colab

En Google Colab podemos trabajar con Python.  
Python incluye una librería llamada `sqlite3`, que nos permite crear una base de datos local y probar comandos SQL.

Primero vamos a importar la librería y crear una conexión.

In [ ]:
import sqlite3
import pandas as pd

conexion = sqlite3.connect("ejemplo_bd.db")
cursor = conexion.cursor()

print("Conexión realizada correctamente.")

Conexión realizada correctamente.

# 5. Creación de una tabla

Vamos a crear una tabla llamada `usuarios`.

Esta tabla tendrá:
- `id`: identificador único
- `nombre`: nombre del usuario
- `correo`: correo electrónico
- `edad`: edad del usuario

Observa que `id` será la **clave primaria**.

In [ ]:
cursor.execute('''
CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    correo TEXT NOT NULL,
    edad INTEGER
)
''')

conexion.commit()
print("Tabla 'usuarios' creada correctamente.")

Tabla 'usuarios' creada correctamente.

## Explicación del comando anterior

- `CREATE TABLE` crea una tabla.
- `IF NOT EXISTS` evita error si la tabla ya existe.
- `id INTEGER PRIMARY KEY AUTOINCREMENT` crea un identificador automático.
- `nombre TEXT NOT NULL` indica que el nombre es texto y no puede quedar vacío.
- `correo TEXT NOT NULL` hace lo mismo para el correo.
- `edad INTEGER` guarda números enteros.

Esto ya se parece al inicio de un sistema real.

# 6. Insertar datos: ALTAS

Cuando en un sistema registramos un nuevo usuario, producto, cliente o alumno, estamos realizando un **alta**.

En SQL esto suele hacerse con `INSERT INTO`.

In [ ]:
usuarios_iniciales = [
    ("Ana", "ana@gmail.com", 22),
    ("Luis", "luis@gmail.com", 25),
    ("María", "maria@gmail.com", 20),
    ("Carlos", "carlos@gmail.com", 28)
]

cursor.executemany(
    "INSERT INTO usuarios (nombre, correo, edad) VALUES (?, ?, ?)",
    usuarios_iniciales
)

conexion.commit()
print("Datos insertados correctamente.")

Datos insertados correctamente.

## ¿Qué pasó aquí?

- `INSERT INTO usuarios` indica en qué tabla guardaremos los datos.
- `(nombre, correo, edad)` indica qué columnas llenaremos.
- `VALUES (?, ?, ?)` usa parámetros para insertar valores de forma ordenada.
- `executemany()` permite insertar varios registros a la vez.

En un sistema web, esta operación puede ocurrir cuando el usuario llena un formulario y presiona **Guardar**.

# 7. Consultar datos: BÚSQUEDAS

La búsqueda de información se realiza con `SELECT`.

Primero veremos todos los registros de la tabla.

In [ ]:
consulta = "SELECT * FROM usuarios"
df_usuarios = pd.read_sql_query(consulta, conexion)
df_usuarios

   id  nombre            correo  edad
0   1     Ana     ana@gmail.com    22
1   2    Luis    luis@gmail.com    25
2   3   María   maria@gmail.com    20
3   4  Carlos  carlos@gmail.com    28

## Explicación

- `SELECT` significa seleccionar.
- `*` significa “todas las columnas”.
- `FROM usuarios` indica de qué tabla se obtendrán los datos.

Esta es la operación más común en pantallas de consulta, listados y reportes.

# 8. Búsqueda con condiciones

Ahora consultaremos solo usuarios mayores de 22 años.

In [ ]:
consulta = "SELECT * FROM usuarios WHERE edad > 22"
df_filtrado = pd.read_sql_query(consulta, conexion)
df_filtrado

   id  nombre            correo  edad
0   2    Luis    luis@gmail.com    25
1   4  Carlos  carlos@gmail.com    28

## Explicación

La cláusula `WHERE` se usa para aplicar condiciones.

Ejemplos:
- `WHERE edad > 22`
- `WHERE nombre = 'Ana'`
- `WHERE correo LIKE '%gmail.com%'`

Esto es muy útil cuando el sistema permite búsquedas por nombre, edad, correo, categoría, fecha, etc.

# 9. Actualizar datos: CAMBIOS

Cuando modificamos información existente, usamos `UPDATE`.

Supongamos que Ana cambió de edad o capturamos mal el dato y queremos corregirlo.

In [ ]:
cursor.execute('''
UPDATE usuarios
SET edad = 23
WHERE nombre = 'Ana'
''')

conexion.commit()
print("Registro actualizado correctamente.")

Registro actualizado correctamente.

In [ ]:
pd.read_sql_query("SELECT * FROM usuarios", conexion)

## Explicación

- `UPDATE usuarios` indica qué tabla se modificará.
- `SET edad = 23` define el nuevo valor.
- `WHERE nombre = 'Ana'` indica qué registro se modificará.

**Advertencia importante:**  
Si haces `UPDATE` sin `WHERE`, podrías modificar **todos** los registros.  
Eso ya no sería una práctica de bases de datos. Sería deporte extremo.

# 10. Eliminar datos: BAJAS

Cuando quitamos un registro, usamos `DELETE`.

Eliminaremos a Carlos de la tabla.

In [ ]:
cursor.execute('''
DELETE FROM usuarios
WHERE nombre = 'Carlos'
''')

conexion.commit()
print("Registro eliminado correctamente.")

Registro eliminado correctamente.

In [ ]:
pd.read_sql_query("SELECT * FROM usuarios", conexion)

   id nombre           correo  edad
0   1    Ana    ana@gmail.com    23
1   2   Luis   luis@gmail.com    25
2   3  María  maria@gmail.com    20

## Explicación

- `DELETE FROM usuarios` indica de qué tabla se eliminará.
- `WHERE nombre = 'Carlos'` define qué registro borrar.

**Advertencia:**  
Igual que con `UPDATE`, si haces `DELETE` sin `WHERE`, podrías eliminar todos los registros.

# 11. Relación con el proyecto web de los alumnos

Tu proyecto consiste en un sistema web con:

- altas,
- bajas,
- cambios,
- búsquedas.

Eso significa que tu sistema necesitará, como mínimo, una tabla bien diseñada y operaciones SQL como estas:

| Acción en el sistema | Operación SQL |
|---|---|
| Registrar un dato | INSERT |
| Consultar un dato | SELECT |
| Modificar un dato | UPDATE |
| Eliminar un dato | DELETE |

## Entonces, ¿qué recomienda este cuadernillo?

Para un proyecto web inicial, conviene trabajar con una estructura clara:

1. **Definir qué información guardarán**
2. **Diseñar las tablas**
3. **Definir la clave primaria**
4. **Establecer reglas básicas**
5. **Probar operaciones CRUD**
6. **Conectar la base de datos con la parte web**

## Ejemplo de sistemas que podrían hacer

- sistema de alumnos
- sistema de clientes
- sistema de productos
- sistema de citas
- sistema de empleados
- sistema de biblioteca

Si apenas van empezando, lo ideal es que elijan un caso sencillo pero bien hecho.

# 12. Diseño básico de una base de datos para un sistema web

Vamos a imaginar que el proyecto será un sistema web para gestionar **productos**.

Cada producto tendrá:

- id
- nombre
- categoría
- precio
- stock

Primero creamos una nueva tabla.

In [ ]:
cursor.execute('''
CREATE TABLE IF NOT EXISTS productos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nombre TEXT NOT NULL,
    categoria TEXT NOT NULL,
    precio REAL NOT NULL,
    stock INTEGER NOT NULL
)
''')

conexion.commit()
print("Tabla 'productos' creada correctamente.")

Tabla 'productos' creada correctamente.

## ¿Por qué esta tabla funciona bien?

Porque tiene estructura clara:

- un identificador único,
- datos descriptivos,
- datos numéricos,
- y campos obligatorios.

Ese tipo de diseño ayuda a que el sistema web sea ordenado desde el inicio.

# 13. Probar CRUD en la tabla productos
## Altas

In [ ]:
productos = [
    ("Laptop", "Tecnología", 14500.50, 10),
    ("Mouse", "Tecnología", 250.00, 35),
    ("Teclado", "Tecnología", 480.00, 20),
    ("Silla", "Mobiliario", 1800.00, 8)
]

cursor.executemany(
    "INSERT INTO productos (nombre, categoria, precio, stock) VALUES (?, ?, ?, ?)",
    productos
)

conexion.commit()
pd.read_sql_query("SELECT * FROM productos", conexion)

   id   nombre   categoria   precio  stock
0   1   Laptop  Tecnología  14500.5     10
1   2    Mouse  Tecnología    250.0     35
2   3  Teclado  Tecnología    480.0     20
3   4    Silla  Mobiliario   1800.0      8

## Búsqueda

In [ ]:
pd.read_sql_query(
    "SELECT * FROM productos WHERE categoria = 'Tecnología'",
    conexion
)

   id   nombre   categoria   precio  stock
0   1   Laptop  Tecnología  14500.5     10
1   2    Mouse  Tecnología    250.0     35
2   3  Teclado  Tecnología    480.0     20

## Cambios

In [ ]:
cursor.execute('''
UPDATE productos
SET stock = 15
WHERE nombre = 'Laptop'
''')
conexion.commit()

pd.read_sql_query("SELECT * FROM productos", conexion)

   id   nombre   categoria   precio  stock
0   1   Laptop  Tecnología  14500.5     15
1   2    Mouse  Tecnología    250.0     35
2   3  Teclado  Tecnología    480.0     20
3   4    Silla  Mobiliario   1800.0      8

## Bajas

In [ ]:
cursor.execute('''
DELETE FROM productos
WHERE nombre = 'Mouse'
''')
conexion.commit()

pd.read_sql_query("SELECT * FROM productos", conexion)

   id   nombre   categoria   precio  stock
0   1   Laptop  Tecnología  14500.5     15
1   3  Teclado  Tecnología    480.0     20
2   4    Silla  Mobiliario   1800.0      8

# 14. Buenas prácticas básicas

Aunque estén iniciando, hay algunas prácticas que conviene adoptar desde ahora.

## 1. Usar nombres claros
Nombres como `usuarios`, `productos`, `clientes` ayudan mucho más que nombres ambiguos.

## 2. Definir una clave primaria
Toda tabla debería tener un identificador único.

## 3. Evitar datos repetidos innecesariamente
Si el mismo dato se repite muchas veces sin necesidad, el diseño puede mejorarse.

## 4. Pensar antes de crear
Antes de programar, conviene responder:
- ¿qué voy a guardar?
- ¿qué voy a consultar?
- ¿qué voy a modificar?
- ¿qué voy a eliminar?

## 5. Probar casos reales
No basta con que “corra”.  
Debe funcionar con lógica.

Ejemplo:
- ¿qué pasa si el nombre está vacío?
- ¿qué pasa si el precio es negativo?
- ¿qué pasa si se quiere buscar un producto que no existe?

# 15. ¿Cómo se conecta esto con una página web?

En un sistema web normalmente existen tres partes:

## 1. Frontend
Es la parte visual que ve el usuario:
- formularios
- botones
- tablas
- buscadores

Puede hacerse con:
- HTML
- CSS
- JavaScript

## 2. Backend
Es la parte lógica del sistema.
Recibe datos del formulario, los valida y ejecuta acciones.

Puede hacerse con:
- Python + Flask
- Python + Django
- PHP
- Java
- Node.js

## 3. Base de datos
Es donde se almacenan los datos de forma permanente.

Puede usarse:
- SQLite para pruebas o proyectos pequeños,
- MySQL o PostgreSQL para proyectos web más formales.

## Recomendación para tus alumnos

Como van empezando y su sistema es web, una ruta muy razonable sería:

- **Frontend:** HTML + CSS + un poco de JavaScript
- **Backend:** Python con Flask
- **Base de datos:** SQLite al principio, y después MySQL si quieren escalar

Esta combinación es muy buena para aprender porque:
- no es tan pesada,
- permite entender bien la lógica,
- y conecta muy bien con CRUD.

# 16. Ejemplo simple de lógica CRUD en Python

Aquí mostraremos una función por cada operación básica.  
No es aún una aplicación web completa, pero sí permite entender la lógica que usaría el backend.

In [ ]:
def alta_producto(nombre, categoria, precio, stock):
    cursor.execute(
        "INSERT INTO productos (nombre, categoria, precio, stock) VALUES (?, ?, ?, ?)",
        (nombre, categoria, precio, stock)
    )
    conexion.commit()

def buscar_productos():
    return pd.read_sql_query("SELECT * FROM productos", conexion)

def actualizar_precio(nombre, nuevo_precio):
    cursor.execute(
        "UPDATE productos SET precio = ? WHERE nombre = ?",
        (nuevo_precio, nombre)
    )
    conexion.commit()

def eliminar_producto(nombre):
    cursor.execute(
        "DELETE FROM productos WHERE nombre = ?",
        (nombre,)
    )
    conexion.commit()

alta_producto("Monitor", "Tecnología", 3200.00, 7)
buscar_productos()

   id   nombre   categoria   precio  stock
0   1   Laptop  Tecnología  14500.5     15
1   3  Teclado  Tecnología    480.0     20
2   4    Silla  Mobiliario   1800.0      8
3   5  Monitor  Tecnología   3200.0      7

## ¿Qué representa esto?

Representa la lógica que más adelante puede conectarse con:

- un botón de guardar,
- una caja de búsqueda,
- una pantalla de edición,
- un botón de eliminar.

Es decir, aquí ya está la idea central del backend.

# Responde lo siguiente:

## Parte A. Comprensión
Responde con tus palabras:

1. ¿Qué es una base de datos?
2. ¿Qué diferencia hay entre tabla, campo y registro?
3. ¿Para qué sirve una clave primaria?
4. ¿Qué hace `SELECT`?
5. ¿Qué hace `UPDATE`?

## Parte B. Práctica
Usando la tabla `productos`:

1. Inserta 3 productos nuevos.
2. Realiza una consulta donde se muestren solo los productos con stock mayor a 5.
3. Cambia el precio de uno de los productos.
4. Elimina un producto.
5. Muestra la tabla final.

## Parte C. Análisis
Explica cómo estas acciones se relacionan con un sistema web real.

## Ejercicio

Tus alumnos ya tienen un proyecto web donde gestionan **altas, bajas, cambios y búsquedas**.  
Con base en ello, deberán proponer y desarrollar en Colab una base de datos sencilla para su sistema.

### Instrucciones del ejercicio final

1. Elige una temática para el sistema.  
   Ejemplos:
   - alumnos
   - clientes
   - productos
   - empleados
   - citas
   - libros

2. Diseña una tabla principal con al menos 5 campos.  
   Debe incluir:
   - una clave primaria,
   - al menos 2 campos de texto,
   - al menos 1 campo numérico.

3. Crea la tabla en SQLite desde Colab.

4. Inserta mínimo 5 registros.

5. Realiza las siguientes operaciones:
   - 2 altas
   - 1 baja
   - 2 cambios
   - 3 búsquedas distintas

6. Muestra capturas o tablas con los resultados.

7. Finalmente, redacta una reflexión breve donde expliques:
   - cómo funcionaría esa base de datos dentro de su sistema web,
   - qué información almacenaría,
   - qué pantallas o formularios necesitaría su sistema.

## Producto esperado

Entregar un cuadernillo de Colab que incluya:

- explicación breve del sistema elegido,
- creación de la tabla,
- inserción de datos,
- operaciones CRUD,
- reflexión final.

## Sugerencia docente

Para alumnos que apenas empiezan, la mejor recomendación es que su proyecto web sea:

- pequeño,
- claro,
- funcional,
- y bien explicado.

No necesitan hacer “el próximo Amazon”.  
Con que no explote el `DELETE` sin `WHERE`, vamos ganando.